# Generated by Django 3.1.5 on 2021-02-09 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_text', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Sender_User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('ps', models.CharField(max_length=200)),
                ('aptNm', models.CharField(blank=True, max_length=200, null=True)),
                ('complexNm', models.CharField(blank=True, max_length=200, null=True)),
                ('villageNm', models.CharField(blank=True, max_length=200, null=True)),
                ('aptAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('notice_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.notice')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sender_user'),
        ),
        migrations.CreateModel(
            name='Message_User',
            fields=[
                ('user_phoneNumber', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=200)),
                ('user_dong', models.CharField(max_length=50)),
                ('user_hosu', models.CharField(max_length=50)),
                ('message_User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sender_user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('individual_notice_text', models.CharField(max_length=1200)),
                ('notice_url', models.CharField(max_length=600, primary_key=True, serialize=False, unique=True)),
                ('isConfirmbyReceiver', models.BooleanField(default=False)),
                ('notice_Confirm_date', models.DateTimeField(verbose_name='date')),
                ('notice_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.notice')),
                ('notice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.sender_user')),
                ('user_phoneNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.message_user')),
            ],
        ),
    ]
