# Generated by Django 3.1.5 on 2021-01-19 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message_User',
            fields=[
                ('user_phoneNumber', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_date', models.DateTimeField(verbose_name='date published')),
                ('notice_title', models.CharField(max_length=200)),
                ('notice_key', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('notice_text', models.CharField(max_length=600)),
                ('notice_url', models.CharField(max_length=600, primary_key=True, serialize=False, unique=True)),
                ('isConfirmbyReceiver', models.BooleanField(default=False)),
                ('notice_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.notice')),
                ('user_phoneNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.message_user')),
            ],
        ),
    ]
